name: "Verify Provenance"
description: "Checks PRs for code provenance against a source repository or refreshes fingerprint databases."
inputs:
  mode:
    description: "Operation mode: check or refresh"
    required: false
    default: "check"
  source_repo:
    description: "The source repository (e.g., redis/redis)"
    required: true
  target_repo:
    description: "The target repository (e.g., valkey-io/valkey)"
    required: true
  branding_pairs:
    description: 'Comma-separated Source:Target brand pairs (e.g., Redis:Valkey,KeyDB:Valkey)'
    required: false
  prefix_pairs:
    description: 'Comma-separated Source:Target prefix pairs (e.g., RM_:VM_)'
    required: false
  source_brand:
    description: "Brand name in source repo"
    required: true
  target_brand:
    description: "Brand name in target repo"
    required: true
  source_prefix:
    description: "Prefix in source"
    required: false
  target_prefix:
    description: "Prefix in target"
    required: false
  github_token:
    description: "GitHub token"
    required: true
  db_branch:
    description: "Orphan branch for databases"
    required: false
    default: "verify-provenance-db"
  pr_db_file:
    description: "Filename of PR database"
    required: false
    default: "pr_fingerprints.json.gz"
  commit_db_file:
    description: "Filename of commit database"
    required: false
    default: "commits_bootstrap.json.gz"
  cutoff_date:
    description: "Cutoff date for refresh (ISO 8601)"
    required: false
    default: "2024-03-20T00:00:00Z"
  threshold:
    description: "Similarity threshold"
    required: false
    default: "0.85"

runs:
  using: "composite"
  steps:
    - name: Fetch Provenance Database
      shell: bash
      run: |
        git fetch origin ${{ inputs.db_branch }}:${{ inputs.db_branch }} --depth 1 || echo "Warning: DB branch not found"
        mkdir -p .provenance-db
        git show ${{ inputs.db_branch }}:${{ inputs.pr_db_file }} > .provenance-db/${{ inputs.pr_db_file }} 2>/dev/null || echo "No PR DB found"
        git show ${{ inputs.db_branch }}:${{ inputs.commit_db_file }} > .provenance-db/${{ inputs.commit_db_file }} 2>/dev/null || echo "No Commit DB found"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Run Operation
      id: op
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PYTHONPATH: ${{ github.action_path }}/src
      run: |
        if [ "${{ inputs.mode }}" = "refresh" ]; then
          owner=$(echo "${{ inputs.source_repo }}" | cut -d/ -f1)
          name=$(echo "${{ inputs.source_repo }}" | cut -d/ -f2)
          python3 ${{ github.action_path }}/src/refresh_prs.py             --source-owner "$owner"             --source-repo-name "$name"             --cutoff-date "${{ inputs.cutoff_date }}"             --out-db ".provenance-db/${{ inputs.pr_db_file }}"             --branding-pairs "${{ inputs.branding_pairs }}" --prefix-pairs "${{ inputs.prefix_pairs }}" --source-brand "${{ inputs.source_brand }}"             --target-brand "${{ inputs.target_brand }}"             --source-prefix "${{ inputs.source_prefix }}"             --target-prefix "${{ inputs.target_prefix }}"

          # Move refreshed file to a known location for the caller to commit
          cp ".provenance-db/${{ inputs.pr_db_file }}" .refreshed_pr_db.json.gz
        else
          PR_NUMBER="${{ github.event.pull_request.number }}"
          python3 ${{ github.action_path }}/src/check.py             $PR_NUMBER             --source-repo "${{ inputs.source_repo }}"             --target-repo "${{ inputs.target_repo }}"             --branding-pairs "${{ inputs.branding_pairs }}" --prefix-pairs "${{ inputs.prefix_pairs }}" --source-brand "${{ inputs.source_brand }}"             --target-brand "${{ inputs.target_brand }}"             --source-prefix "${{ inputs.source_prefix }}"             --target-prefix "${{ inputs.target_prefix }}"             --pr-db ".provenance-db/${{ inputs.pr_db_file }}"             --commit-db ".provenance-db/${{ inputs.commit_db_file }}"             --threshold "${{ inputs.threshold }}"             --verbose 2> .provenance-output.log

          EXIT_CODE=$?
          if [ $EXIT_CODE -eq 1 ] && grep -q "matches" .provenance-output.log; then
            echo "provenance_failed=true" >> $GITHUB_OUTPUT
            cat .provenance-output.log
          fi
          exit $EXIT_CODE
        fi

    - name: Post Results to PR
      if: failure() && steps.op.outputs.provenance_failed == 'true' && inputs.mode == 'check'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        COMMENT="### ❌ Provenance Check Alert
        
        Potential code similarities detected with upstream repository.
        
        "
        MATCHES=$(grep "matches" .provenance-output.log | sed "s/^[0-9:-]* \[INFO\] //" | sed "s/^/ - /")
        COMMENT="${COMMENT}${MATCHES}
        
        ---
        *This check was performed automatically by the Provenance Guard Action.*"
        REPO="${{ inputs.target_repo }}"
        PR_NUMBER="${{ github.event.pull_request.number }}"
          JSON_BODY=$(python3 -c 'import json,sys; print(json.dumps({"body": sys.argv[1]}))' "$COMMENT")
          curl -s -X POST -H "Authorization: Bearer ${GITHUB_TOKEN}"              -H "Accept: application/vnd.github+json"              "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments"              -d "$JSON_BODY"
